<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Viajar</name>
   <tag></tag>
   <elementGuidId>c24e38fa-55be-4fc3-81e6-6b263153db4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rf-header__submenu-link.rf-header__submenu-link--caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rf-header-top/div[1]/div[1]/ul[1]/li[1]/rf-submenu[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rf-header__submenu-link rf-header__submenu-link--caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Viajar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentPage&quot;)/div[@class=&quot;root responsivegrid rf-general__content&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;experiencefragment aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;cmp-experiencefragment cmp-experiencefragment--header&quot;]/div[@class=&quot;xf-content-height&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;responsivegrid aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;rfheader image aem-GridColumn aem-GridColumn--default--12&quot;]/rf-header[@class=&quot;rf-header-wrapper hydrated&quot;]/rf-header-top[@class=&quot;rf-header hydrated open&quot;]/div[@class=&quot;rf-header__container container&quot;]/div[@class=&quot;rf-header__wrap-menu grid&quot;]/ul[@class=&quot;rf-header__principal&quot;]/li[@class=&quot;rf-header__submenu&quot;]/rf-submenu[@class=&quot;rf-submenu hydrated open&quot;]/span[@class=&quot;rf-header__submenu-link rf-header__submenu-link--caret&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentPage']/div/div/div/div/div/div/div/div/div/rf-header/rf-header-top/div/div/ul/li/rf-submenu/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifas'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billetes'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Viajar']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
   </webElementXpaths>
</WebElementEntity>
